#!/bin/bash

set -o errexit -o nounset

buildDir="dist"

commitSha=$(git rev-parse --short HEAD)
commitAuthorName=$(git --no-pager show -s --format='%an' HEAD)
commitAuthorEmail=$(git --no-pager show -s --format='%ae' HEAD)
commitMessage=$(git log --oneline -n 1)
branch=$TRAVIS_BRANCH

repoName="novo-elements-snapshot"
repoUrl="https://github.com/bullhorn/novo-elements-snapshot.git"
repoDir="snapshot"

echo "Cloning $repoUrl into $repoDir"
git clone $repoUrl $repoDir

echo "Changing branch to $branch"
git checkout -B $branch

echo "Cleaning snapshot repo and moving build files into it"
rm -rf $repoDir/*
cp -r $buildDir/* $repoDir
cd $repoDir

# Prepare Git for pushing the artifacts to the repository.
git config user.name "$commitAuthorName"
git config user.email "$commitAuthorEmail"
git config credential.helper "store --file=.git/credentials"

echo "https://${SNAPSHOT_GIT_TOKEN}:@github.com" > .git/credentials

git add -A
git commit -m "$commitMessage"

if [ "$branch" == "master" ]; then
    echo "Committing and pushing to master"
    git tag "$commitSha"
    git push origin master --tags
else
    echo "Committing and pushing to $branch"
    git push -u origin $branch
fi

echo "Finished publishing snapshot build to $branch"
