/**
 * AUTOGENERATED FILE - DO NOT EDIT
 * Generated by: https://bhsource.bullhorn.com/DEV_WORKSPACE/country-state-parser
 * Last generated on: Fri Apr 12 2024 10:17:16 GMT-0400 (Eastern Daylight Time)
 */
export declare const COUNTRIES: Country[];
/**
 * Gets all countries
 */
export declare function getCountries(): string[];
/**
 * Gets a country by country ID
 */
export declare function findByCountryId(id: number): Country | undefined;
/**
 * Gets a country by country name
 * @param name - Name of country to find
 */
export declare function findByCountryName(name: string): Country | undefined;
/**
 * Gets a country by country code
 * @param code - Code of country to find
 */
export declare function findByCountryCode(code: string): Country | undefined;
/**
 * Gets states by country name
 * @param name - Name of the country to search by
 */
export declare function getStateObjects(name: string): State[];
/**
 * Gets state names by country name
 * @param name - Name of the country to search by
 */
export declare function getStates(name: string): string[];
/**
 * Interfaces for State and Country objects
 */
export interface State {
    code: string;
    name: string;
}
export interface Country {
    code: string;
    id: number;
    name: string;
    states: State[];
}
