// Vendor
import { DateCell, NovoDropdownCell, PercentageCell } from 'novo-elements';
import { ActionsCellExample } from './custom-cells/actions-cell-example';

export const HEADER_COLORS = ['aqua', 'ocean', 'mint', 'grass', 'sunflower', 'company', 'lead', 'positive', 'black'];

export const TableColumns = [
  { title: 'Actions', renderer: ActionsCellExample, sorting: false, filtering: false },
  { title: 'Name', name: 'name', ordering: true, type: 'link', filtering: true },
  { title: 'Position', name: 'position', ordering: true, filtering: true },
  {
    title: 'Extn.',
    name: 'ext',
    ordering: true,
    renderer: (object) => {
      return object.ext.obj;
    },
    compare: (sort, previous, current) => {
      let first = previous.obj,
        second = current.obj;

      if (first > second) {
        return sort === 'desc' ? -1 : 1;
      }
      if (first < second) {
        return sort === 'asc' ? -1 : 1;
      }
      return 0;
    },
  },
  {
    title: 'Start date',
    type: 'date',
    name: 'startDate',
    renderer: DateCell,
    ordering: true,
    filtering: true,
    range: true,
  },
  {
    title: '%',
    name: 'percent',
    ordering: true,
    renderer: PercentageCell,
  },
  {
    title: 'Salary',
    name: 'salary',
    ordering: true,
    renderer: (object) => {
      return `$ ${Number(object.salary).toFixed(2)}`;
    },
  },
  {
    title: 'Status',
    name: 'status',
    renderer: NovoDropdownCell,
    dropdownCellConfig: [
      {
        category: 'Update Status',
        callback: (data: any, status: string) => window.alert(`Update Status ${status}!`),
        options: [{ label: 'New Lead', value: 'New Lead' }, { label: 'Active', value: 'Active' }, { label: 'Archived', value: 'Archived' }],
      },
      {
        category: 'Move',
        callback: (data: any, status: string) => window.alert(`Move ${status}!`),
        options: ['Kitten', 'Kitty'],
      },
      {
        callback: (data: any, status: string) => window.alert(`Move ${status}!`),
        options: ['Meow', 'Kitty'],
      },
    ],
  },
];

export const TableData = [
  {
    name: 'Victoria Cantrell',
    position: 'Integer Corporation',
    office: 'Croatia',
    ext: { obj: '8262' },
    startDate: new Date('2017/08/19'),
    salary: 208178,
    percent: 0.5,
    status: 'New Lead',
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Pearl Crosby',
    position: 'In PC',
    office: 'Cambodia',
    ext: { obj: '8262' },
    startDate: new Date('2017/10/08'),
    salary: 114367,
    percent: 0.5,
    status: 'New Lead',
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Colette Foley',
    position: 'Lorem Inc.',
    office: 'Korea, North',
    ext: { obj: '8262' },
    startDate: new Date('2017/07/19'),
    salary: 721473,
    status: 'New Lead',
    percent: 1,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Anastasia Shaffer',
    position: 'Dolor Nulla Semper LLC',
    office: 'Suriname',
    ext: { obj: '8262' },
    startDate: new Date('2017/04/20'),
    salary: 264620,
    percent: 1,
    status: 'New Lead',
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Gabriel Castro',
    position: 'Sed Limited',
    office: 'Bahrain',
    ext: { obj: '8262' },
    startDate: new Date('2017/03/04'),
    salary: 651350,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Cherokee Ware',
    position: 'Tincidunt LLC',
    office: 'United Kingdom (Great Britain)',
    ext: { obj: '8262' },
    startDate: new Date('2017/06/17'),
    salary: 666259,
    status: 'New Lead',
    percent: 0.25,
    description:
      'It’s been a long time coming, but tonight, because of what we did on this day, in this election, at this defining time, change has come to America.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Barry Moss',
    position: 'Sociis Industries',
    office: 'Western Sahara',
    ext: { obj: '8262' },
    startDate: new Date('2017/08/13'),
    salary: 541631,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Maryam Tucker',
    position: 'Elit Pede Malesuada Inc.',
    office: 'Brazil',
    ext: { obj: '8262' },
    startDate: new Date('2017/10/02'),
    salary: 182294,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Constance Clayton',
    position: 'Auctor Velit Aliquam LLP',
    office: 'United Arab Emirates',
    ext: { obj: '8262' },
    startDate: new Date('2017/08/01'),
    salary: 218597,
    percent: 0.33,
    status: 'New Lead',
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Rogan Tucker',
    position: 'Arcu Vestibulum Ante Associates',
    office: 'Jersey',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/04'),
    salary: 861632,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Emery Mcdowell',
    position: 'Gravida Company',
    office: 'New Zealand',
    ext: { obj: '8262' },
    startDate: new Date('2017/06/02'),
    salary: 413568,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Yael Greer',
    position: 'Orci Limited',
    office: 'Madagascar',
    ext: { obj: '8262' },
    startDate: new Date('2017/12/04'),
    salary: 121831,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Jared Burgess',
    position: 'Auctor Incorporated',
    office: 'Burundi',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/12'),
    salary: 62243,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Sharon Campbell',
    position: 'Elit Curabitur Sed Consulting',
    office: 'Comoros',
    ext: { obj: '8262' },
    startDate: new Date('2017/09/14'),
    salary: 200854,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Finance'],
  },
  {
    name: 'Yeo Church',
    position: 'Donec Vitae Erat PC',
    office: 'Saudi Arabia',
    ext: { obj: '8262' },
    startDate: new Date('2017/06/07'),
    salary: 581193,
    status: 'New Lead',
    percent: 0.25,
    description:
      'To my campaign manager David Plouffe, my chief strategist David Axelrod, and the best campaign team ever assembled in the history of politics – you made this happen, and I am forever grateful for what you’ve sacrificed to get it done.',
    categories: ['Temporary', 'Finance'],
  },
  {
    name: 'Kylie Barlow',
    position: 'Fermentum Risus Corporation',
    office: 'Papua New Guinea',
    ext: { obj: '8262' },
    startDate: new Date('2017/12/03'),
    salary: 418115,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Temporary', 'Finance'],
  },
  {
    name: 'Nell Leonard',
    position: 'Vestibulum Consulting',
    office: 'Saudi Arabia',
    ext: { obj: '8262' },
    startDate: new Date('2017/05/29'),
    salary: 466201,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Temporary', 'Finance'],
  },
  {
    name: 'Brandon Fleming',
    position: 'Donec Egestas Associates',
    office: 'Poland',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/22'),
    salary: 800011,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Temporary', 'Finance'],
  },
  {
    name: 'Inga Pena',
    position: 'Et Magnis Dis Limited',
    office: 'Belgium',
    ext: { obj: '8262' },
    startDate: new Date('2017/05/18'),
    salary: 564245,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Permenant', 'Finance'],
  },
  {
    name: 'Arden Russo',
    position: 'Est Tempor Bibendum Corp.',
    office: 'Dominican Republic',
    ext: { obj: '8262' },
    startDate: new Date('2017/07/23'),
    salary: 357222,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Permenant', 'Finance'],
  },
  {
    name: 'Liberty Gallegos',
    position: 'Nec Diam LLC',
    office: 'Ghana',
    ext: { obj: '8262' },
    startDate: new Date('2017/06/18'),
    salary: 554375,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Permenant', 'Developer'],
  },
  {
    name: 'Dennis York',
    position: 'Nullam Suscipit Foundation',
    office: 'Namibia',
    ext: { obj: '8262' },
    startDate: new Date('2017/03/20'),
    salary: 90417,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Permenant', 'Developer'],
  },
  {
    name: 'Petra Chandler',
    position: 'Pede Nonummy Inc.',
    office: 'Namibia',
    ext: { obj: '8262' },
    startDate: new Date('2017/03/26'),
    salary: 598915,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Permenant', 'Developer'],
  },
  {
    name: 'Aurelia Marshall',
    position: 'Donec Consulting',
    office: 'Nicaragua',
    ext: { obj: '8262' },
    startDate: new Date('2017/08/18'),
    salary: 201780,
    status: 'New Lead',
    percent: 0.25,
    description:
      'And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world – our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down – we will defeat you. To those who seek peace and security – we support you. And to all those who have wondered if America’s beacon still burns as bright – tonight we proved once more that the true strength of our nation comes not from our the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity, and unyielding hope.',
    categories: ['Permenant', 'Developer'],
  },
  {
    name: 'Rose Carter',
    position: 'Enim Consequat Purus Industries',
    office: 'Morocco',
    ext: { obj: '8262' },
    startDate: new Date('2017/03/06'),
    salary: 220187,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Permenant', 'Developer'],
  },
  {
    name: 'Denton Atkins',
    position: 'Non Vestibulum PC',
    office: 'Mali',
    ext: { obj: '8262' },
    startDate: new Date('2017/04/19'),
    salary: 324588,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Permenant', 'Developer'],
  },
  {
    name: 'Germaine Osborn',
    position: 'Tristique Aliquet PC',
    office: 'Lesotho',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/19'),
    salary: 351108,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Nell Butler',
    position: 'Sit Amet Dapibus Industries',
    office: 'Cuba',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/06'),
    salary: 230072,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Marketing'],
  },
  {
    name: 'Brent Stein',
    position: 'Eu Augue Porttitor LLP',
    office: 'Cyprus',
    ext: { obj: '8262' },
    startDate: new Date('2017/11/02'),
    salary: 853413,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Marketing'],
  },
  {
    name: 'Alexandra Shaw',
    position: 'Aenean Gravida Limited',
    office: 'Uruguay',
    ext: { obj: '8262' },
    startDate: new Date('2017/05/16'),
    salary: 401970,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Marketing'],
  },
  {
    name: 'Veronica Allison',
    position: 'Aliquet Diam Sed Institute',
    office: 'Samoa',
    ext: { obj: '8262' },
    startDate: new Date('2017/05/17'),
    salary: 79193,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Marketing'],
  },
  {
    name: 'Katelyn Gamble',
    position: 'Sed Associates',
    office: 'Mauritius',
    ext: { obj: '8262' },
    startDate: new Date('2017/03/20'),
    salary: 484299,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Marketing'],
  },
  {
    name: 'James Greer',
    position: 'A Dui Incorporated',
    office: 'Norway',
    ext: { obj: '8262' },
    startDate: new Date('2017/02/21'),
    salary: 333518,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Marketing'],
  },
  {
    name: 'Cain Vasquez',
    position: 'Nulla Facilisis Suspendisse Institute',
    office: 'China',
    ext: { obj: '8262' },
    startDate: new Date('2017/05/27'),
    salary: 651761,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Marketing'],
  },
  {
    name: 'Shaeleigh Barr',
    position: 'Eleifend Cras Institute',
    office: 'Ghana',
    ext: { obj: '8262' },
    startDate: new Date('2017/04/01'),
    salary: 627095,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Developer'],
  },
  {
    name: 'Baker Mckay',
    position: 'Ut Sagittis Associates',
    office: 'Isle of Man',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/12'),
    salary: 742247,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Developer'],
  },
  {
    name: 'Jayme Pace',
    position: 'Cras Eu Tellus Associates',
    office: 'Bouvet Island',
    ext: { obj: '8262' },
    startDate: new Date('2017/08/12'),
    salary: 591588,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Developer'],
  },
  {
    name: 'Reuben Albert',
    position: 'Lobortis Institute',
    office: 'Zambia',
    ext: { obj: '8262' },
    startDate: new Date('2017/04/04'),
    salary: 791408,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Developer'],
  },
  {
    name: 'Idola Burns',
    position: 'Non Industries',
    office: 'Myanmar',
    ext: { obj: '8262' },
    startDate: new Date('2017/06/24'),
    salary: 142906,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Contractor', 'Developer'],
  },
  {
    name: 'Laura Macias',
    position: 'Phasellus Inc.',
    office: 'Mauritania',
    ext: { obj: '8262' },
    startDate: new Date('2017/11/21'),
    salary: 226591,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Nichole Salas',
    position: 'Duis PC',
    office: 'Madagascar',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/18'),
    salary: 234196,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Hunter Walter',
    position: 'Ullamcorper Duis Cursus Foundation',
    office: 'Brazil',
    ext: { obj: '8262' },
    startDate: new Date('2017/02/28'),
    salary: 655052,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Asher Rich',
    position: 'Mauris Ipsum LLP',
    office: 'Paraguay',
    ext: { obj: '8262' },
    startDate: new Date('2017/08/08'),
    salary: 222946,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Angela Carlson',
    position: 'Donec Tempor Institute',
    office: 'Papua New Guinea',
    ext: { obj: '8262' },
    startDate: new Date('2017/02/12'),
    salary: 562194,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'James Dorsey',
    position: 'Ipsum Leo Associates',
    office: 'Congo (Brazzaville)',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/10'),
    salary: 629925,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Wesley Cobb',
    position: 'Nunc Est Incorporated',
    office: 'Australia',
    ext: { obj: '8262' },
    startDate: new Date('2017/01/30'),
    salary: 343476,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Meghan Stephens',
    position: 'Interdum PC',
    office: 'Turkey',
    ext: { obj: '8262' },
    startDate: new Date('2017/10/11'),
    salary: 469305,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Bertha Herrera',
    position: 'Amet Limited',
    office: 'Kenya',
    ext: { obj: '8262' },
    startDate: new Date('2018/11/22'),
    salary: 56606,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Karina Key',
    position: 'Quisque Varius Nam Company',
    office: 'France',
    ext: { obj: '8262' },
    startDate: new Date('2018/03/26'),
    salary: 314260,
    status: 'New Lead',
    percent: 0.25,
    description:
      'I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the Vice President-elect of the United States, Joe Biden.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Uriel Carson',
    position: 'Penatibus PC',
    office: 'Venezuela',
    ext: { obj: '8262' },
    startDate: new Date('2018/01/07'),
    salary: 106335,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Mira Baird',
    position: 'Felis Orci PC',
    office: 'Niue',
    ext: { obj: '8262' },
    startDate: new Date('2018/08/25'),
    salary: 515671,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Ursula Parrish',
    position: 'Ac Corporation',
    office: 'Macao',
    ext: { obj: '8262' },
    startDate: new Date('2018/06/30'),
    salary: 72295,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Josephine Sykes',
    position: 'Blandit Congue Limited',
    office: 'Holy See (Vatican City State)',
    ext: { obj: '8262' },
    startDate: new Date('2018/12/22'),
    salary: 694656,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Maggie Sims',
    position: 'Vulputate Posuere Industries',
    office: 'Sudan',
    ext: { obj: '8262' },
    startDate: new Date('2018/11/22'),
    salary: 363743,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Rogan Fuentes',
    position: 'Vestibulum Accumsan Neque Company',
    office: 'Jersey',
    ext: { obj: '8262' },
    startDate: new Date('2018/07/29'),
    salary: 606004,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Maya Haney',
    position: 'Ac Foundation',
    office: 'Falkland Islands',
    ext: { obj: '8262' },
    startDate: new Date('2016/09/03'),
    salary: 745500,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Aquila Battle',
    position: 'Sociis Natoque Penatibus Foundation',
    office: 'Azerbaijan',
    ext: { obj: '8262' },
    startDate: new Date('2016/03/06'),
    salary: 582265,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Connor Coleman',
    position: 'Orci Lacus Vestibulum Foundation',
    office: 'Croatia',
    ext: { obj: '8262' },
    startDate: new Date('2016/10/21'),
    salary: 416958,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Charity Thomas',
    position: 'Convallis Ligula Donec Inc.',
    office: 'Benin',
    ext: { obj: '8262' },
    startDate: new Date('2016/07/12'),
    salary: 540999,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Developer'],
  },
  {
    name: 'Blythe Powers',
    position: 'Amet Orci Limited',
    office: 'Falkland Islands',
    ext: { obj: '8262' },
    startDate: new Date('2016/01/23'),
    salary: 480067,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Human Resources'],
  },
  {
    name: 'Adria Battle',
    position: 'Ornare Lectus Incorporated',
    office: 'British Indian Ocean Territory',
    ext: { obj: '8262' },
    startDate: new Date('2016/05/28'),
    salary: 257937,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Human Resources'],
  },
  {
    name: 'Melanie Mcintyre',
    position: 'Nunc Corp.',
    office: 'Mongolia',
    ext: { obj: '8262' },
    startDate: new Date('2016/01/06'),
    salary: 359737,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Human Resources'],
  },
  {
    name: 'Keely Bauer',
    position: 'Nec Tempus Institute',
    office: 'Somalia',
    ext: { obj: '8262' },
    startDate: new Date('2016/03/09'),
    salary: 99718,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Human Resources'],
  },
  {
    name: 'Noelani Strong',
    position: 'Nec LLP',
    office: 'Iran',
    ext: { obj: '8262' },
    startDate: new Date('2016/08/24'),
    salary: 480718,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Communications', 'Human Resources'],
  },
  {
    name: 'Jeanette Henderson',
    position: 'Eu Elit Nulla Corporation',
    office: 'Italy',
    ext: { obj: '8262' },
    startDate: new Date('2016/06/19'),
    salary: 253772,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Candace Huber',
    position: 'Sed Institute',
    office: 'Uganda',
    ext: { obj: '8262' },
    startDate: new Date('2016/06/16'),
    salary: 388879,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Bethany Potter',
    position: 'Vivamus Nibh Dolor Incorporated',
    office: 'Puerto Rico',
    ext: { obj: '8262' },
    startDate: new Date('2016/11/12'),
    salary: 747310,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Whoopi Burks',
    position: 'Justo Inc.',
    office: 'Fiji',
    ext: { obj: '8262' },
    startDate: new Date('2016/09/24'),
    salary: 803037,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Sheila Long',
    position: 'Diam Associates',
    office: 'Sao Tome and Principe',
    ext: { obj: '8262' },
    startDate: new Date('2016/12/21'),
    salary: 674379,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Sonya Church',
    position: 'Laoreet Institute',
    office: 'Grenada',
    ext: { obj: '8262' },
    startDate: new Date('2016/06/03'),
    salary: 625147,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Shaine Forbes',
    position: 'Eu Arcu LLP',
    office: 'Cyprus',
    ext: { obj: '8262' },
    startDate: new Date('2016/01/18'),
    salary: 208100,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Alexandra Patrick',
    position: 'Ligula Donec Inc.',
    office: 'Viet Nam',
    ext: { obj: '8262' },
    startDate: new Date('2016/04/09'),
    salary: 104063,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Patience Vincent',
    position: 'Sem Molestie Associates',
    office: 'Philippines',
    ext: { obj: '8262' },
    startDate: new Date('2016/07/04'),
    salary: 673556,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Evelyn Smith',
    position: 'Fusce Industries',
    office: 'Togo',
    ext: { obj: '8262' },
    startDate: new Date('2016/08/15'),
    salary: 737284,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Kieran Gonzalez',
    position: 'Non Corp.',
    office: 'Equatorial Guinea',
    ext: { obj: '8262' },
    startDate: new Date('2016/08/24'),
    salary: 90195,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Molly Oneil',
    position: 'Non Dui Consulting',
    office: 'Belize',
    ext: { obj: '8262' },
    startDate: new Date('2016/10/28'),
    salary: 140767,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Nigel Davenport',
    position: 'Ullamcorper Velit In Industries',
    office: 'Vanuatu',
    ext: { obj: '8262' },
    startDate: new Date('2016/03/16'),
    salary: 70536,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Thor Young',
    position: 'Malesuada Consulting',
    office: 'French Southern Territories',
    ext: { obj: '8262' },
    startDate: new Date('2016/01/28'),
    salary: 75501,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Finn Delacruz',
    position: 'Lorem Industries',
    office: 'Cocos (Keeling) Islands',
    ext: { obj: '8262' },
    startDate: new Date('2016/12/11'),
    salary: 754967,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Lane Henderson',
    position: 'Pede Foundation',
    office: 'Kazakhstan',
    ext: { obj: '8262' },
    startDate: new Date('2016/07/02'),
    salary: 842050,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Shea Potter',
    position: 'Curabitur Limited',
    office: 'Timor-Leste',
    ext: { obj: '8262' },
    startDate: new Date('2016/05/07'),
    salary: 263629,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Brynn Yang',
    position: 'Ut Limited',
    office: 'Mayotte',
    ext: { obj: '8262' },
    startDate: new Date('2016/01/17'),
    salary: 74292,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Kylan Fuentes',
    position: 'Sapien Aenean Associates',
    office: 'Brazil',
    ext: { obj: '8262' },
    startDate: new Date('2016/12/28'),
    salary: 108632,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Lionel Mcbride',
    position: 'Ipsum PC',
    office: 'Portugal',
    ext: { obj: '8262' },
    startDate: new Date('2016/07/11'),
    salary: 34244,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Paul Lucas',
    position: 'Eget LLP',
    office: 'Nicaragua',
    ext: { obj: '8262' },
    startDate: new Date('2016/09/30'),
    salary: 690834,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Lareina Williamson',
    position: 'Imperdiet Ullamcorper Ltd',
    office: 'Cocos (Keeling) Islands',
    ext: { obj: '8262' },
    startDate: new Date('2016/12/01'),
    salary: 603498,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Amy Acevedo',
    position: 'Id Institute',
    office: 'Cook Islands',
    ext: { obj: '8262' },
    startDate: new Date('2016/02/04'),
    salary: 125165,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Nomlanga Silva',
    position: 'Eget LLC',
    office: 'Belize',
    ext: { obj: '8262' },
    startDate: new Date('2016/01/31'),
    salary: 268509,
    status: 'New Lead',
    percent: 0.25,
    description: 'Labore sit nulla amet enim reprehenderit esse laborum Lorem quis in eu.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Amena Stone',
    position: 'Enim Incorporated',
    office: 'Guinea',
    ext: { obj: '8262' },
    startDate: new Date('2016/09/23'),
    salary: 214381,
    status: 'New Lead',
    percent: 0.25,
    description:
      'There was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Danielle Coffey',
    position: 'Feugiat Placerat Corp.',
    office: 'Sao Tome and Principe',
    ext: { obj: '8262' },
    startDate: new Date('2016/06/17'),
    salary: 137423,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Temporary', 'Developer'],
  },
  {
    name: 'Buffy Russell',
    position: 'Lacus Quisque Ltd',
    office: 'Ecuador',
    ext: { obj: '8262' },
    startDate: new Date('2016/10/17'),
    salary: 612184,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Kaitlin Lamb',
    position: 'Malesuada Fringilla Est Associates',
    office: 'Algeria',
    ext: { obj: '8262' },
    startDate: new Date('2016/10/18'),
    salary: 327367,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Leilani Yates',
    position: 'Mus Proin LLC',
    office: 'South Sudan',
    ext: { obj: '8262' },
    startDate: new Date('2016/05/27'),
    salary: 743493,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Jemima Moon',
    position: 'Phasellus Corp.',
    office: 'South Georgia and The South Sandwich Islands',
    ext: { obj: '8262' },
    startDate: new Date('2016/05/21'),
    salary: 496067,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Hiroko Schwartz',
    position: 'Neque Institute',
    office: 'Saint Vincent and The Grenadines',
    ext: { obj: '8262' },
    startDate: new Date('2016/03/13'),
    salary: 178782,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Nathaniel Jensen',
    position: 'Mi Tempor Limited',
    office: 'Dominica',
    ext: { obj: '8262' },
    startDate: new Date('2018/12/05'),
    salary: 37441,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Silas Sweeney',
    position: 'Ultrices Institute',
    office: 'Turkmenistan',
    ext: { obj: '8262' },
    startDate: new Date('2018/11/13'),
    salary: 152980,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Jermaine Barry',
    position: 'Dapibus Corporation',
    office: 'Uzbekistan',
    ext: { obj: '8262' },
    startDate: new Date('2018/03/06'),
    salary: 409463,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Tatiana Nichols',
    position: 'Nec Diam Industries',
    office: 'Cook Islands',
    ext: { obj: '8262' },
    startDate: new Date('2018/05/22'),
    salary: 51155,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
  {
    name: 'Rama Waller',
    position: 'Sem Pellentesque LLC',
    office: 'Andorra',
    ext: { obj: '8262' },
    startDate: new Date('2018/12/01'),
    salary: 223227,
    status: 'New Lead',
    percent: 0.25,
    description:
      'When there was despair in the dust bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes we can.',
    categories: ['Office Skills'],
  },
];
