export interface State {
  code: string;
  name: string;
  abbr: string;
}

export const STATES: Array<State> = [
  { name: 'Alabama', abbr: 'Ala.', code: 'AL' },
  { name: 'Alaska', abbr: 'Alaska', code: 'AK' },
  { name: 'Arizona', abbr: 'Ariz.', code: 'AZ' },
  { name: 'Arkansas', abbr: 'Ark.', code: 'AR' },
  { name: 'California', abbr: 'Calif.', code: 'CA' },
  { name: 'Colorado', abbr: 'Colo.', code: 'CO' },
  { name: 'Connecticut', abbr: 'Conn.', code: 'CT' },
  { name: 'Delaware', abbr: 'Del.', code: 'DE' },
  { name: 'District of Columbia', abbr: 'D.C.', code: 'DC' },
  { name: 'Florida', abbr: 'Fla.', code: 'FL' },
  { name: 'Georgia', abbr: 'Ga.', code: 'GA' },
  { name: 'Hawaii', abbr: 'Hawaii', code: 'HI' },
  { name: 'Idaho', abbr: 'Idaho', code: 'ID' },
  { name: 'Illinois', abbr: 'Ill.', code: 'IL' },
  { name: 'Indiana', abbr: 'Ind.', code: 'IN' },
  { name: 'Iowa', abbr: 'Iowa', code: 'IA' },
  { name: 'Kansas', abbr: 'Kans.', code: 'KS' },
  { name: 'Kentucky', abbr: 'Ky.', code: 'KY' },
  { name: 'Louisiana', abbr: 'La.', code: 'LA' },
  { name: 'Maine', abbr: 'Maine', code: 'ME' },
  { name: 'Maryland', abbr: 'Md.', code: 'MD' },
  { name: 'Massachusetts', abbr: 'Mass.', code: 'MA' },
  { name: 'Michigan', abbr: 'Mich.', code: 'MI' },
  { name: 'Minnesota', abbr: 'Minn.', code: 'MN' },
  { name: 'Mississippi', abbr: 'Miss.', code: 'MS' },
  { name: 'Missouri', abbr: 'Mo.', code: 'MO' },
  { name: 'Montana', abbr: 'Mont.', code: 'MT' },
  { name: 'Nebraska', abbr: 'Nebr.', code: 'NE' },
  { name: 'Nevada', abbr: 'Nev.', code: 'NV' },
  { name: 'New Hampshire', abbr: 'N.H.', code: 'NH' },
  { name: 'New Jersey', abbr: 'N.J.', code: 'NJ' },
  { name: 'New Mexico', abbr: 'N.M.', code: 'NM' },
  { name: 'New York', abbr: 'N.Y.', code: 'NY' },
  { name: 'North Carolina', abbr: 'N.C.', code: 'NC' },
  { name: 'North Dakota', abbr: 'N.D.', code: 'ND' },
  { name: 'Ohio', abbr: 'Ohio', code: 'OH' },
  { name: 'Oklahoma', abbr: 'Okla.', code: 'OK' },
  { name: 'Oregon', abbr: 'Ore.', code: 'OR' },
  { name: 'Pennsylvania', abbr: 'Pa.', code: 'PA' },
  { name: 'Rhode Island', abbr: 'R.I.', code: 'RI' },
  { name: 'South Carolina', abbr: 'S.C.', code: 'SC' },
  { name: 'South Dakota', abbr: 'S.D.', code: 'SD' },
  { name: 'Tennessee', abbr: 'Tenn.', code: 'TN' },
  { name: 'Texas', abbr: 'Tex.', code: 'TX' },
  { name: 'Utah', abbr: 'Utah', code: 'UT' },
  { name: 'Vermont', abbr: 'Vt.', code: 'VT' },
  { name: 'Virginia', abbr: 'Va.', code: 'VA' },
  { name: 'Washington', abbr: 'Wash.', code: 'WA' },
  { name: 'West Virginia', abbr: 'W.Va.', code: 'WV' },
  { name: 'Wisconsin', abbr: 'Wis.', code: 'WI' },
  { name: 'Wyoming', abbr: 'Wyo.', code: 'WY' },
];
