// NG2
import { ScrollingModule } from '@angular/cdk/scrolling';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { NovoAceEditorModule, NovoDragulaModule, NovoDragulaService, NovoNovoCKEditorModule } from 'novo-elements/addons';
import { NovoCommonModule, NovoOptionModule, NovoOverlayModule } from 'novo-elements/common';
import {
  GooglePlacesModule,
  GooglePlacesService,
  NovoAgendaModule,
  NovoAsideModule,
  NovoAvatarModule,
  NovoBreadcrumbModule,
  NovoButtonModule,
  NovoCalendarModule,
  NovoCardModule,
  NovoCategoryDropdownModule,
  NovoCheckboxModule,
  NovoChipsModule,
  NovoColorPickerModule,
  NovoDataTableModule,
  NovoDatePickerModule,
  NovoDateTimePickerModule,
  NovoDividerModule,
  NovoDropdownModule,
  NovoExpansionModule,
  NovoFieldModule,
  NovoFlexModule,
  NovoFormExtrasModule,
  NovoFormModule,
  NovoHeaderModule,
  NovoIconModule,
  NovoLayoutModule,
  NovoListModule,
  NovoLoadingModule,
  NovoMenuModule,
  NovoModalModule,
  NovoMultiPickerModule,
  NovoNonIdealStateModule,
  NovoPickerModule,
  NovoPopOverModule,
  NovoProgressModule,
  NovoQueryBuilderModule,
  NovoQuickNoteModule,
  NovoRadioModule,
  NovoSearchBoxModule,
  NovoSelectModule,
  NovoSelectSearchModule,
  NovoSliderModule,
  NovoStepperModule,
  NovoSwitchModule,
  NovoTabbedGroupPickerModule,
  NovoTableModule,
  NovoTabModule,
  NovoTilesModule,
  NovoTimePickerModule,
  NovoTipWellModule,
  NovoToastModule,
  NovoToolbarModule,
  NovoTooltipModule,
  NovoValueModule,
  UnlessModule,
} from 'novo-elements/components';
import { FormUtils } from 'novo-elements/components/form';
import { NovoPipesModule } from 'novo-elements/pipes';
import {
  BrowserGlobalRef,
  ComponentUtils,
  DateFormatService,
  GlobalRef,
  LocalStorageService,
  NovoLabelService,
  OptionsService,
} from 'novo-elements/services';

@NgModule({
  imports: [ReactiveFormsModule],
  exports: [
    NovoAsideModule,
    NovoAvatarModule,
    NovoPipesModule,
    NovoButtonModule,
    NovoLoadingModule,
    NovoCardModule,
    NovoAgendaModule,
    NovoCalendarModule,
    NovoCheckboxModule,
    NovoFlexModule,
    NovoLayoutModule,
    NovoDividerModule,
    NovoToastModule,
    NovoTooltipModule,
    NovoHeaderModule,
    NovoTabModule,
    NovoTilesModule,
    NovoModalModule,
    NovoQuickNoteModule,
    NovoRadioModule,
    NovoDropdownModule,
    NovoSelectModule,
    NovoListModule,
    NovoSwitchModule,
    NovoDragulaModule,
    NovoSliderModule,
    NovoPickerModule,
    NovoChipsModule,
    NovoDatePickerModule,
    NovoTimePickerModule,
    NovoDateTimePickerModule,
    NovoNovoCKEditorModule,
    NovoTipWellModule,
    NovoTableModule,
    NovoFormModule,
    NovoFormExtrasModule,
    NovoCategoryDropdownModule,
    NovoMultiPickerModule,
    NovoPopOverModule,
    NovoDataTableModule,
    NovoSearchBoxModule,
    NovoProgressModule,
    NovoOverlayModule,
    GooglePlacesModule,
    NovoValueModule,
    NovoAceEditorModule,
    NovoIconModule,
    NovoExpansionModule,
    UnlessModule,
    NovoCommonModule,
    NovoOptionModule,
    NovoStepperModule,
    NovoToolbarModule,
    ScrollingModule,
    NovoTabbedGroupPickerModule,
    NovoNonIdealStateModule,
    NovoBreadcrumbModule,
    NovoFieldModule,
    NovoColorPickerModule,
    NovoMenuModule,
    NovoSelectSearchModule,
    NovoQueryBuilderModule,
  ],
  providers: [
    { provide: ComponentUtils, useClass: ComponentUtils },
    { provide: DateFormatService, useClass: DateFormatService },
    { provide: NovoLabelService, useClass: NovoLabelService },
    { provide: NovoDragulaService, useClass: NovoDragulaService },
    { provide: GooglePlacesService, useClass: GooglePlacesService },
    { provide: GlobalRef, useClass: BrowserGlobalRef },
    { provide: LocalStorageService, useClass: LocalStorageService },
    { provide: OptionsService, useClass: OptionsService },
    { provide: FormUtils, useClass: FormUtils },
  ],
})
export class NovoElementsModule {}
