import * as i0 from "@angular/core";
import * as i1 from "@angular/forms";
import * as i2 from "novo-elements/elements";
import * as i3 from "novo-elements/pipes";
import * as i4 from "novo-elements/addons";
import * as i5 from "@angular/cdk/scrolling";
export declare class NovoElementsModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<NovoElementsModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<NovoElementsModule, never, [typeof i1.ReactiveFormsModule], [typeof i2.NovoAsideModule, typeof i2.NovoAutoCompleteModule, typeof i2.NovoAvatarModule, typeof i3.NovoPipesModule, typeof i2.NovoButtonModule, typeof i2.NovoLoadingModule, typeof i2.NovoCardModule, typeof i2.NovoAgendaModule, typeof i2.NovoCalendarModule, typeof i2.NovoCheckboxModule, typeof i2.NovoFlexModule, typeof i2.NovoLayoutModule, typeof i2.NovoDividerModule, typeof i2.NovoToastModule, typeof i2.NovoTooltipModule, typeof i2.NovoHeaderModule, typeof i2.NovoTabModule, typeof i2.NovoTilesModule, typeof i2.NovoModalModule, typeof i2.NovoQuickNoteModule, typeof i2.NovoRadioModule, typeof i2.NovoDropdownModule, typeof i2.NovoSelectModule, typeof i2.NovoListModule, typeof i2.NovoSwitchModule, typeof i2.NovoSliderModule, typeof i2.NovoPickerModule, typeof i2.NovoChipsModule, typeof i2.NovoDatePickerModule, typeof i2.NovoTimePickerModule, typeof i2.NovoDateTimePickerModule, typeof i4.NovoNovoCKEditorModule, typeof i2.NovoTipWellModule, typeof i2.NovoSimpleTableModule, typeof i2.NovoFormModule, typeof i2.NovoFormExtrasModule, typeof i2.NovoCategoryDropdownModule, typeof i2.NovoMultiPickerModule, typeof i2.NovoPopOverModule, typeof i2.NovoDataTableModule, typeof i2.NovoSearchBoxModule, typeof i2.NovoProgressModule, typeof i2.NovoOverlayModule, typeof i2.NovoDragDropModule, typeof i2.GooglePlacesModule, typeof i2.NovoValueModule, typeof i4.NovoAceEditorModule, typeof i4.NovoCodeEditorModule, typeof i2.NovoIconModule, typeof i2.NovoExpansionModule, typeof i2.UnlessModule, typeof i2.NovoCommonModule, typeof i2.NovoOptionModule, typeof i2.NovoStepperModule, typeof i2.NovoToolbarModule, typeof i5.ScrollingModule, typeof i2.NovoTabbedGroupPickerModule, typeof i2.NovoNonIdealStateModule, typeof i2.NovoBreadcrumbModule, typeof i2.NovoFieldModule, typeof i2.NovoColorPickerModule, typeof i2.NovoMenuModule, typeof i2.NovoSelectSearchModule, typeof i2.NovoQueryBuilderModule]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<NovoElementsModule>;
}
