import { automationId } from './SelectorUtil';

export const toolbarSelectors = {
    basicToolbar: automationId('basic-toolbar'),
    accentToolbar: automationId('toolbar-accent'),
    companyToolbar: automationId('toolbar-company'),
    companyOverviewTab: automationId('toolbar-company-overview-tab'),
    companyFilesTab: automationId('toolbar-company-files-tab'),
    companyButton: automationId('toolbar-company-button'),
    companyShareAction: automationId('toolbar-company-share-action'),
    companyPrintAction: automationId('toolbar-company-print-action'),
    companyCloseAction: automationId('toolbar-company-close-action'),
    navigationToolbar: automationId('toolbar-navigation'),
    navMenuAction: automationId('toolbar-nav-menu-action'),
    navLogo: automationId('toolbar-nav-logo'),
    navAddAction: automationId('toolbar-nav-add-action'),
    navSearch: automationId('toolbar-nav-search'),
    navSupportAction: automationId('toolbar-nav-support-action'),
    navSettingsAction: automationId('toolbar-nav-settings-action'),
    navAvatar: automationId('toolbar-nav-avatar'),
    multiRowToolbar: automationId('multi-row-toolbar'),
    toolbarRowHeader: automationId('toolbar-row-header'),
    toolbarRowHeaderMenu: automationId('toolbar-row-header-menu'),
    toolbarRowNav: automationId('toolbar-row-nav'),
    toolbarNavOverviewTab: automationId('toolbar-nav-overview-tab'),
    toolbarNavActivityTab: automationId('toolbar-nav-activity-tab'),
    toolbarNavFilesTab: automationId('toolbar-nav-files-tab'),
    toolbarRowNavLayoutBtn: automationId('toolbar-row-nav-layout-btn'),
};
