name: Release Novo Elements
on: 
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Dry Run

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.0
      - name: Install Dependencies
        run: npm ci
      - name: Build Novo Elements
        run: npm run build:ci
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
